FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml poetry.lock* /app/

RUN pip install pipx
RUN pipx install poetry
RUN pipx ensurepath

COPY . /app

CMD ["~/.local/bin/poetry", "run", "python", "main.py"] 